# Optimized for dev 

# ref: https://nodejs.org/en/docs/guides/nodejs-docker-webapp/
# ref: https://github.com/Zenika/alpine-chrome#run-examples
# ref: https://www.npmjs.com/package/aws-lambda-ric # see this for lambda + 2-stage build instructions

# Define custom function directory
ARG FUNCTION_DIR="/function"


###############################
# Docker Build Stage 1
###############################

FROM node:14.16.0-buster

# Include global arg in this stage of the build
ARG FUNCTION_DIR
WORKDIR ${FUNCTION_DIR}


# Multi-stage dep install to leverage docker layer caching 

# Stage 1: Install system deps
RUN apt update
RUN apt-get install -y \
  g++ \
  make \
  cmake \
  unzip \
  autoconf \
  libtool \
  libcurl4-openssl-dev \
  python3 \
  rsync
# Install chrome
RUN apt install -y wget
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt install -y ./google-chrome-stable_current_amd64.deb

# Stage 2: Pre-build aws-lambda-ric so that we dont need rebuild on every change to package.json
RUN npm init -y &> /dev/null
RUN npm i aws-lambda-ric
RUN mv node_modules aws_node_modules

# Stage 3: Copy package*.json and install deps
COPY package*.json ./
RUN npm i

# Stage 4: Merge aws-lambda-ric deps
RUN rsync -ar aws_node_modules/ node_modules

# Stage 5: Copy remaining source files
COPY . .

# Stage 6: Transpile typescript
RUN npx tsc


ENTRYPOINT ["/usr/bin/npx", "aws-lambda-ric"]
CMD ["app.handler"]